
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: configprops,env,health,info,logfile,loggers,metrics,prometheus
server:
    port: 8080
    shutdown: graceful
spring:
    application:
        name: sathishruns
    data:
        jpa:
            repositories:
                bootstrap-mode: deferred
    datasource:
        hikari:
            auto-commit: false
    flyway:
        locations: classpath:/db/migration/{vendor}
        validate-on-migrate: false
    jmx:
        enabled: false
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                connection:
                    provider_disables_autocommit: true
                generate_statistics: false
                jdbc:
                    batch_size: 25
                    lob:
                        non_contextual_creation: true
                    time_zone: UTC
                order_inserts: true
                order_updates: true
                query:
                    fail_on_pagination_over_collection_fetch: true
                    in_clause_parameter_padding: true
                    plan_cache_max_size: 4096
        show-sql: true
    main:
        allow-bean-definition-overriding: true
    mvc:
        problemdetails:
            enabled: true
decorator:
    datasource:
        datasource-proxy:
            json-format: true
            format-sql: true

        flexy-pool:
            threshold:
                connection:
                    acquire: -1
                    lease: 0

